{"email": "web@uwo.ca", "url": "https://uwo.ca/about/contact.html"}
{"email": "media@uwo.ca", "url": "https://uwo.ca/about/contact.html"}
{"email": "alumni@uwo.ca", "url": "https://uwo.ca/about/contact.html"}
{"email": "international@uwo.ca", "url": "https://uwo.ca/about/contact.html"}
{"email": "liaison@uwo.ca", "url": "https://uwo.ca/about/contact.html"}
{"email": "travelregistry@uwo.ca", "url": "https://international.uwo.ca/learning/"}
{"email": "music@uwo.ca", "url": "https://music.uwo.ca/"}
{"email": "goabroad@uwo.ca", "url": "https://international.uwo.ca/learning/"}
{"email": "contact@uwo.ca", "url": "https://www.registrar.uwo.ca/academics/distance_studies.html"}
{"email": "arts@uwo.ca", "url": "https://www.uwo.ca/arts/"}
{"email": "contactwe@eng.uwo.ca", "url": "https://www.eng.uwo.ca/"}
{"email": "education@uwo.ca", "url": "https://www.edu.uwo.ca/"}
{"email": "privacy.office@uwo.ca", "url": "https://www.uwo.ca/vpfinance/legalcounsel/privacy/"}
{"email": "web@uwo.ca", "url": "https://www.uwo.ca/about/contact.html"}
{"email": "contactWE@eng.uwo.ca", "url": "https://www.eng.uwo.ca/"}
{"email": "dlapkow@uwo.ca", "url": "https://www.uwo.ca/vpfinance/legalcounsel/privacy/"}
{"email": "media@uwo.ca", "url": "https://www.uwo.ca/about/contact.html"}
{"email": "alumni@uwo.ca", "url": "https://www.uwo.ca/about/contact.html"}
{"email": "international@uwo.ca", "url": "https://www.uwo.ca/about/contact.html"}
{"email": "liaison@uwo.ca", "url": "https://www.uwo.ca/about/contact.html"}
{"email": "joann.johnston@uwo.ca", "url": "https://www.uwo.ca/community/"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=148"}
{"email": "es-ugrd-grd-coordinator@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=64"}
{"email": "vagrads@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=148"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=64"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=146"}
{"email": "ase@uwo.ca", "url": "http://academicsupport.uwo.ca"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=244"}
{"email": "vagrads@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=146"}
{"email": "jquinn2@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=244"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=147"}
{"email": "vagrads@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=147"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/web_design/standards/"}
{"email": "ahuffma2@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/communications.html"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/terms_of_use.html"}
{"email": "acamp266@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/communications.html"}
{"email": "swoods42@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/communications.html"}
{"email": "cvonwist@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/communications.html"}
{"email": "deb.vanbrenk@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/communications.html"}
{"email": "cpowel4@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/communications.html"}
{"email": "ttesta2@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/communications.html"}
{"email": "mdeguzm5@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/communications.html"}
{"email": "mrobb9@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/communications.html"}
{"email": "cyi8@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/communications.html"}
{"email": "jrenaud9@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/communications.html"}
{"email": "crystal.mackay@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/communications.html"}
{"email": "asteve27@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/communications.html"}
{"email": "eamaya@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/communications.html"}
{"email": "chaberm@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/communications.html"}
{"email": "joann.johnston@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/communications.html"}
{"email": "a.blackburnevans@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/communications.html"}
{"email": "sander76@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/communications.html"}
{"email": "dlahteen@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/communications.html"}
{"email": "sledgley@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/communications.html"}
{"email": "mcheate@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/communications.html"}
{"email": "mrobb9@uwo.com", "url": "https://communications.uwo.ca/teams-expertise/communications.html"}
{"email": "jjohn352@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/communications.html"}
{"email": "kferg28@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/communications.html"}
{"email": "steyaert@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/communications.html"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/communications.html"}
{"email": "mhoy6@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/communications.html"}
{"email": "JoAnn.Johnston@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/communications.html"}
{"email": "rpotte@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/communications.html"}
{"email": "twalker2@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/communications.html"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/western_brand/rebrand_faqs.html"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/western_brand/spirit.html"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=144"}
{"email": "srice@huron.uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=143"}
{"email": "westernid@uwo.ca", "url": "https://communications.uwo.ca/western_brand/email_signature.html"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=145"}
{"email": "mcaldwe2@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=144"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=143"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/western_brand/email_signature.html"}
{"email": "mcaldwe2@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=145"}
{"email": "jchamb42@uwo.ca", "url": "https://www.westerncalendar.uwo.ca/Pages.cfm?PageID=110&SelectedCalendar=Live&ArchiveID="}
{"email": "leeann.mckivor@uwo.ca", "url": "https://www.westerncalendar.uwo.ca/Pages.cfm?PageID=110&SelectedCalendar=Live&ArchiveID="}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/web_design/standards/layout/index.html"}
{"email": "mrexample@uwo.ca", "url": "https://communications.uwo.ca/web_design/standards/forms.html"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/web_design/standards/columns.html"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/web_design/standards/boxes.html"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/web_design/standards/tables.html"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/web_design/standards/text-over-image.html"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/web_design/standards/forms.html"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/web_design/standards/lists.html"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/web_design/standards/buttons.html"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/index.html"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/web_design/standards/interactive_elements/index.html"}
{"email": "french@uwo.ca", "url": "https://www.westerncalendar.uwo.ca/Modules.cfm?ModuleID=20944&SelectedCalendar=Live&ArchiveID="}
{"email": "french@uwo.ca", "url": "https://www.westerncalendar.uwo.ca/Departments.cfm?DepartmentID=50&SelectedCalendar=Live&ArchiveID="}
{"email": "wecareer@uwo.ca", "url": "https://www.westerncalendar.uwo.ca/Modules.cfm?ModuleID=21654&SelectedCalendar=Live&ArchiveID="}
{"email": "accting@uwo.ca", "url": "https://wts.uwo.ca/about-wts/contact.html"}
{"email": "Dept-Faculty@groups.uwo.ca", "url": "https://wts.uwo.ca/office_365/groups_distribution_groups.html"}
{"email": "Dept-All@groups.uwo.ca", "url": "https://wts.uwo.ca/office_365/groups_distribution_groups.html"}
{"email": "tjrice@uwo.ca", "url": "https://communications.uwo.ca/western_brand/graphic_standards.html"}
{"email": "tjrice@uwo.ca", "url": "https://communications.uwo.ca/western_brand/vis_toolkit/index.html"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/western_brand/graphic_standards.html"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/western_brand/vis_toolkit/index.html"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/web_design/events_calendar.html"}
{"email": "social@uwo.ca", "url": "https://communications.uwo.ca/web_design/social_media/index.html"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/web_design/checklist.html"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/western_brand/index.html"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/web_design/writing/index.html"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/web_design/seo.html"}
{"email": "calendar@uwo.ca", "url": "https://communications.uwo.ca/web_design/events_calendar.html"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/web_design/social_media/index.html"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/web_design/graphics/index.html"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/web_design/image-guidelines/index.html"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/web_design/accessibility/index.html"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/web_design/index.html"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/web_design/standards/index.html"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/news_publications/recruitment.html"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/news_publications/development.html"}
{"email": "annual.giving@uwo.ca", "url": "https://communications.uwo.ca/news_publications/development.html"}
{"email": "wts-sia-information@groups.uwo.ca", "url": "https://wts.uwo.ca/official_emails/index.html"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/news_publications/alumni.html"}
{"email": "webadm@uwo.ca", "url": "https://wts.uwo.ca/spam_phishing/examples/index.html"}
{"email": "jsutherl@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=142"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=141"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=142"}
{"email": "stats-grad-inquiry@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=141"}
{"email": "mrpe@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=285"}
{"email": "publichealth@schulich.uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=114"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=246"}
{"email": "tbwalker@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=139"}
{"email": "tjrice@uwo.ca", "url": "https://communications.uwo.ca/news_publications/index.html"}
{"email": "kdundas2@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/faculty/index.html"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=138"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=140"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=137"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=285"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=114"}
{"email": "cdennist@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=246"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=139"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/news_publications/index.html"}
{"email": "mparke42@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/faculty/index.html"}
{"email": "rrombout@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/faculty/index.html"}
{"email": "grucchin@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/faculty/index.html"}
{"email": "lina.wang@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/faculty/index.html"}
{"email": "jo.jennings@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/faculty/index.html"}
{"email": "jeckel4@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/faculty/index.html"}
{"email": "aroy89@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/faculty/index.html"}
{"email": "nebel@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/faculty/index.html"}
{"email": "jbechar@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/faculty/index.html"}
{"email": "mwolfe24@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/faculty/index.html"}
{"email": "mzimmer4@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/faculty/index.html"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/faculty/index.html"}
{"email": "a.blackburnevans@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/faculty/index.html"}
{"email": "bblue@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/faculty/index.html"}
{"email": "rmilec@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/faculty/index.html"}
{"email": "dkeddy@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/faculty/index.html"}
{"email": "rachel.condie@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/faculty/index.html"}
{"email": "svilovsk@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=138"}
{"email": "stats-grad-inquiry@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=140"}
{"email": "svilovsk@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=137"}
{"email": "localgov@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=269"}
{"email": "localgov@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=131"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=130"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=129"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=127"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=126"}
{"email": "web@uwo.ca", "url": "https://communications.uwo.ca/teams-expertise/index.html"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=242"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=269"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=131"}
{"email": "psygradinfo@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=130"}
{"email": "psygradinfo@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=129"}
{"email": "tmclauch@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=127"}
{"email": "tmclauch@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=126"}
{"email": "cpsx@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=242"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=120"}
{"email": "bdavis66@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=123"}
{"email": "bdavis66@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=122"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=125"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=119"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=118"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=289"}
{"email": "okrougly@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=120"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=123"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=122"}
{"email": "ptadmit@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=125"}
{"email": "philgradoffice@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=119"}
{"email": "philgradoffice@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=118"}
{"email": "zkhan5@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=289"}
{"email": "pathgrad@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=289"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=113"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=111"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=110"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=112"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=109"}
{"email": "smckay27@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=108"}
{"email": "smckay27@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=107"}
{"email": "pathgrad@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=113"}
{"email": "pathgrad@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=111"}
{"email": "gradorthoadmissions@schulich.uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=110"}
{"email": "pathgrad@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=112"}
{"email": "askot@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=109"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=108"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=107"}
{"email": "smckay27@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=106"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=105"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=104"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=103"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=288"}
{"email": "ayardley@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=102"}
{"email": "ayardley@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=98"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=106"}
{"email": "khunt29@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=105"}
{"email": "neuroscience@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=104"}
{"email": "neuroscience@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=103"}
{"email": "jdesou22@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=288"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=102"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=98"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=121"}
{"email": "ayardley@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=101"}
{"email": "mnigradstudies@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=91"}
{"email": "ayardley@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=99"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=239"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=271"}
{"email": "okrougly@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=121"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=101"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=91"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=99"}
{"email": "michael.haan@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=239"}
{"email": "lawgrad@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=271"}
{"email": "mnigradstudies@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=89"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=241"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=240"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=21"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=23"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=96"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=95"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=94"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=89"}
{"email": "scolli72@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=241"}
{"email": "pfoster@robarts.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=240"}
{"email": "askmbp@schulich.uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=21"}
{"email": "askmbp@schulich.uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=23"}
{"email": "slong@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=96"}
{"email": "slong@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=95"}
{"email": "jblom@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=94"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=93"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=92"}
{"email": "math-grad-program@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=85"}
{"email": "math-grad-program@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=84"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=248"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=88"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=83"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=82"}
{"email": "jblom@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=93"}
{"email": "jblom@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=92"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=85"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=84"}
{"email": "bheinric@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=248"}
{"email": "msc@ivey.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=88"}
{"email": "linguist-ma@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=83"}
{"email": "slong@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=82"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=81"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=80"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=79"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=78"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=77"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=75"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=76"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=263"}
{"email": "slong@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=81"}
{"email": "lawgrad@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=80"}
{"email": "lawgrad@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=79"}
{"email": "lawgrad@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=78"}
{"email": "lmbodin@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=77"}
{"email": "lmiles27@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=77"}
{"email": "lmbodin@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=75"}
{"email": "lmiles27@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=75"}
{"email": "lmbodin@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=76"}
{"email": "lmiles27@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=76"}
{"email": "slong@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=263"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=286"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=73"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=72"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=71"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=70"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=69"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=68"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=136"}
{"email": "jfranco@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=286"}
{"email": "kbrow@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=73"}
{"email": "kbrow@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=72"}
{"email": "skontra@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=71"}
{"email": "skontra@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=70"}
{"email": "slong@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=69"}
{"email": "slong@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=68"}
{"email": "hrsinfo@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=136"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=133"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=270"}
{"email": "cmiller@eng.uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=287"}
{"email": "es-ugrd-grd-coordinator@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=67"}
{"email": "es-ugrd-grd-coordinator@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=65"}
{"email": "es-ugrd-grd-coordinator@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=62"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=61"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=60"}
{"email": "hrsinfo@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=133"}
{"email": "nsolomo4@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=270"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=287"}
{"email": "cmorasto@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=287"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=67"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=65"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=62"}
{"email": "ljohns24@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=61"}
{"email": "ljohns24@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=60"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=59"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=302"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=301"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=58"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=57"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=56"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=55"}
{"email": "lmcinnis@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=53"}
{"email": "ljohns24@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=59"}
{"email": "mtayl42@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=302"}
{"email": "mtayl42@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=301"}
{"email": "frgrpr@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=58"}
{"email": "frgrpr@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=57"}
{"email": "fnsgrad@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=56"}
{"email": "mfe@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=55"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=53"}
{"email": "lmcinnis@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=52"}
{"email": "epibio@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=51"}
{"email": "epibio@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=50"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=48"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=47"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=46"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=238"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=290"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=52"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=51"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=50"}
{"email": "hsanders@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=48"}
{"email": "leanne.trask@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=47"}
{"email": "leanne.trask@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=46"}
{"email": "hsanders@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=238"}
{"email": "tceli@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=290"}
{"email": "gkknopf@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=237"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=41"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=40"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=44"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=115"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=117"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=39"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=45"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=237"}
{"email": "ecegrad@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=41"}
{"email": "ecegrad@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=40"}
{"email": "info.graded@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=44"}
{"email": "info.graded@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=115"}
{"email": "info.graded@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=117"}
{"email": "ecegrad@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=39"}
{"email": "info.graded@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=45"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=43"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=42"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=236"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=272"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=38"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=37"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=36"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=35"}
{"email": "econ-gradcoordinator@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=43"}
{"email": "econ-gradcoordinator@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=42"}
{"email": "kburrell@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=236"}
{"email": "bheinric@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=272"}
{"email": "gradsec@csd.uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=38"}
{"email": "gradsec@csd.uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=37"}
{"email": "skontra@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=36"}
{"email": "skontra@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=35"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=34"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=33"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=32"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=31"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=30"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=29"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=2"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=28"}
{"email": "jharman3@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=34"}
{"email": "askmbp@schulich.uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=33"}
{"email": "ewoolno@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=32"}
{"email": "ewoolno@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=31"}
{"email": "civilgrad@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=30"}
{"email": "civilgrad@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=29"}
{"email": "dhagen@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=2"}
{"email": "civilgrad@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=28"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=1"}
{"email": "cbegrad@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=27"}
{"email": "cbegrad@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=26"}
{"email": "cbegrad@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=25"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=87"}
{"email": "teganwu@ivey.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=86"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=24"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=20"}
{"email": "dhagen@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=1"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=27"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=26"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=25"}
{"email": "mba@ivey.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=87"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=86"}
{"email": "phd@ivey.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=24"}
{"email": "bmeoffice@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=20"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=19"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=18"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=17"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=16"}
{"email": "bdavis66@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=13"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=15"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=275"}
{"email": "bdavis66@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=14"}
{"email": "bmeoffice@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=19"}
{"email": "clcurtis@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=18"}
{"email": "clcurtis@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=17"}
{"email": "mluckovi@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=16"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=13"}
{"email": "mluckovi@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=15"}
{"email": "ecegrad@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=275"}
{"email": "gradsec@csd.uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=275"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=14"}
{"email": "adimova2@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=12"}
{"email": "adimova2@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=11"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=274"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=9"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=8"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=7"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=5"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=273"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=12"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=11"}
{"email": "gdahs@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=274"}
{"email": "cwall4@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=9"}
{"email": "cwall4@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=8"}
{"email": "anatomy@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=7"}
{"email": "anatomy@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=5"}
{"email": "ahcp@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=273"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=265"}
{"email": "julie.jonkhans@uwo.ca", "url": "https://www.uwo.ca/ownyourfuture/"}
{"email": "cpa@uwo.ca", "url": "https://grad.uwo.ca/admissions/programs/program.cfm?p=265"}
{"email": "nicole.kuntz@uwo.ca", "url": "https://www.uwo.ca/ownyourfuture/"}
{"email": "ccircel@uwo.ca", "url": "https://grad.uwo.ca/administration/directory.html"}
{"email": "equity@uwo.ca", "url": "https://grad.uwo.ca/career_development/competitive_edge/index.html"}
{"email": "julie.jonkhans@uwo.ca", "url": "https://grad.uwo.ca/administration/directory.html"}
{"email": "cgoff6@uwo.ca", "url": "https://grad.uwo.ca/administration/directory.html"}
{"email": "sogs@uwo.ca", "url": "https://grad.uwo.ca/administration/directory.html"}
{"email": "mdumouc2@uwo.ca", "url": "https://grad.uwo.ca/administration/directory.html"}
{"email": "jtaron2@uwo.ca", "url": "https://grad.uwo.ca/administration/directory.html"}
{"email": "remartin@uwo.ca", "url": "https://grad.uwo.ca/administration/directory.html"}
{"email": "ahoffer@uwo.ca", "url": "https://grad.uwo.ca/administration/directory.html"}
{"email": "mharmos@uwo.ca", "url": "https://grad.uwo.ca/administration/directory.html"}
{"email": "tbroniew@uwo.ca", "url": "https://grad.uwo.ca/administration/directory.html"}
{"email": "cvukson@uwo.ca", "url": "https://grad.uwo.ca/administration/directory.html"}
{"email": "thern2@uwo.ca", "url": "https://grad.uwo.ca/administration/directory.html"}
{"email": "ldavies@uwo.ca", "url": "https://grad.uwo.ca/administration/directory.html"}
{"email": "sscm@uwo.ca", "url": "https://grad.uwo.ca/administration/directory.html"}
{"email": "cbell57@uwo.ca", "url": "https://grad.uwo.ca/administration/directory.html"}
{"email": "gradapps@uwo.ca", "url": "https://grad.uwo.ca/administration/directory.html"}
{"email": "kmaruoka@uwo.ca", "url": "https://grad.uwo.ca/administration/directory.html"}
{"email": "cloosley@uwo.ca", "url": "https://grad.uwo.ca/administration/directory.html"}
{"email": "mwolfe24@uwo.ca", "url": "https://grad.uwo.ca/administration/directory.html"}
{"email": "ron.wagler@uwo.ca", "url": "https://grad.uwo.ca/administration/directory.html"}
{"email": "edaley2@uwo.ca", "url": "https://grad.uwo.ca/administration/directory.html"}
{"email": "klocke2@uwo.ca", "url": "https://grad.uwo.ca/administration/directory.html"}
{"email": "btaylo48@uwo.ca", "url": "https://grad.uwo.ca/administration/directory.html"}
{"email": "pmenzies@uwo.ca", "url": "https://grad.uwo.ca/administration/directory.html"}
{"email": "hrhelp@uwo.ca", "url": "https://grad.uwo.ca/administration/directory.html"}
{"email": "lmiller@uwo.ca", "url": "https://grad.uwo.ca/administration/directory.html"}
{"email": "cmiddaug@uwo.ca", "url": "https://grad.uwo.ca/administration/directory.html"}
{"email": "hrhelp@uwo.ca", "url": "https://grad.uwo.ca/career_development/competitive_edge/index.html"}
{"email": "mharmos@uwo.ca", "url": "https://grad.uwo.ca/career_development/competitive_edge/index.html"}
{"email": "executive@sogs.ca", "url": "https://grad.uwo.ca/life_community/self/index.html"}
{"email": "external@sogs.ca", "url": "https://grad.uwo.ca/life_community/connect/index.html"}
{"email": "services@sogs.ca", "url": "https://grad.uwo.ca/life_community/study/index.html"}
{"email": "executive@sogs.ca", "url": "https://grad.uwo.ca/life_community/play/index.html"}
{"email": "dcampb62@uwo.ca", "url": "https://grad.uwo.ca/life_community/study/index.html"}
{"email": "ncampb47@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "sirons@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "lmeloche@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "kingrad@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "hsanders@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "mbojic2@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "lstaecke@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "asigut@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "tbirming@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "sdoyle3@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "graded@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "csprengl@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "drudman@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "jdesou22@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "smckay27@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "mhaan2@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "nbhatia2@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "mmorr2@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "pmastal@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "charpe5@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "jennifer.plaskett@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "lamarche@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "jharman3@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "jblom@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "gcampbel@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "dmoser22@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "khunt29@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "jimmy.dikeakos@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "ybabenko@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "susan.simpson@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "mkarttu@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "lpurdy@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "speechly@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "aessex@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "dwoolfor@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "egrimes@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "alawend@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "gdevivei@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "kshuey@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "cburucua@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "jpolzer@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "lmbodin@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "bheinric@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "achant2@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "kmooney@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "calcanta@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "ssincla5@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "atassi2@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "jbaxter6@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "lplumme@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "esviride@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "jstarow@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "lrehmann@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "cwall4@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "mluckovi@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "jcuthber@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "beynon@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "mmagowa@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "tmclauch@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "jbbrown@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "tadrysda@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "hfieldin@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "nolivei7@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "lshire@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "lrobich3@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "phernan3@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "aelansa@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "jcambria@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "pdonahu@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "NTIMOTHA@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "jgomezle@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "iluginaa@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "inamukas@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "tbwalker@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "ksiddiq@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "zkhan5@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "lruggeri@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "jlyons7@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "lmurra57@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "nsolomo4@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "abottere@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "jzhan283@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "mfulle7@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "csaund9@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "kbrow@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "dbeer@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "mcaldwe2@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "jpurkis@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "linguist-ma@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "bnikolak@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "cvande42@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "sbarghi2@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "mstudnic@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "marcos.escobar@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "czheng25@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "snavarr@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "ljiang55@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "mtayl48@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "smcclat2@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "sturnbu6@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "amcint4@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "nborrad@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "rhhudson@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "tkoning@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "cpalme45@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "scolli72@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "mmorenom@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "saugust2@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "gzaric@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "slong@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "bshilton@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "awickham@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "sross55@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "vparsa@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "jmiller@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "morrison@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "bborman@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "ewoolno@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "jcopela4@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "svilovsk@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "kkapulki@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "jchew23@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "crosskee@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "ljohns24@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "kwillmo2@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "duffen@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "jgeneau@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "smccar5@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "jjin@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "lmcinnis@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "akraszna@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "edrysda4@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "frgrpr@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "rhallam2@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "dhagen@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "askmbp@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "kburrell@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "mdelgad@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "jsabarin@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "kolson2@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "ltraskro@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "kander42@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "cbarre46@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "lisa.hodgetts@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "khladyni@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "amendel5@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "dllee@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "gshaw1@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "medbiogradchair@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "karen.henry@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "jfstaple@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "jwiersm2@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "ayardley@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "srice@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "shawn.whitehead@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "pmensin@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "zhuan23@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "jfranco@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "gkknopf@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "bvanroes@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "ljmenor@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "hhill6@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "pfoster4@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "eadams29@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "clcurtis@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "ehayden@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "okrougly@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "hgillis3@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "bdavis66@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "skontra@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "jsutherl@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "adimova2@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "jseabro2@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "jdevlin2@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "cnaudi@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "chambide@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "djackows@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "mbutle52@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "lcardoz@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "bcorneil@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
{"email": "rbooth6@uwo.ca", "url": "https://grad.uwo.ca/administration/program_contacts.cfm"}
